name: Track Clone Metrics via GitHub App

on:
  workflow_dispatch:

jobs:
  clone-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allows committing results

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Fetch clone data via GitHub App
        env:
          TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          mkdir -p .metrics
          curl -s -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $TOKEN" \
              https://api.github.com/repos/${{ github.repository }}/traffic/clones \
              > .metrics/clone_stats.json
          cat .metrics/clone_stats.json
        
      - name: Append to CSV log
        run: |
          mkdir -p .metrics
          COUNT=$(jq '.count' .metrics/clone_stats.json)
          UNIQUES=$(jq '.uniques' .metrics/clone_stats.json)
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

          if [ ! -f .metrics/clone_metrics.csv ]; then
            echo "date,total_clones_14d,unique_cloners_14d" > .metrics/clone_metrics.csv
          fi

          echo "$DATE,$COUNT,$UNIQUES" >> .metrics/clone_metrics.csv
          tail -n 3 .metrics/clone_metrics.csv

      - name: Commit and push results
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          git config user.name "CloneMetricsBot[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .metrics/clone_metrics.csv
          git commit -m "Update Clone Metrics" || echo "No changes to commit"
          git push
        
