name: Test GitHub App Token

on:
  workflow_dispatch:

jobs:
  test-app:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Print token prefix
        run: |
          echo "Token starts with:"
          echo "${{ steps.generate_token.outputs.token }}" | cut -c1-30
